name: solat
description: Prayer times.
publish_to: "none"

version: 2.4.0+24

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_typeahead: ^5.2.0
  http: ^1.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "design/Launcher-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald-ExtraLight.ttf
          weight: 100
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
        - asset: assets/fonts/PTSerif-Bold.ttf
          weight: 700
